module VehicleModels
  ALFA_ROMEO = [
      '4C',
      '4C Spider',
      'Giulietta',
      'Mito',
      '159',
      'Brera',
      'GT',
      '147',
  ]

  AUDI = [
      'S8',
      'A8',
      'S7',
      'A7',
      'S6',
      'A6',
      'S4',
      'A4',
      'S3',
      'A3',
      'AB L',
      'RS 7',
      'AB L W12',
      'R8',
      'TT',
      'S5',
      'A5',
      'TTS',
      'RS 5',
      'Q7',
      'SQ 5',
      'Q5',
      'Q3',
      'Allroad',
      'Q5 Hybrid',
      'A3 Sportback e-tron',
      'R8 Spyder',
      'TT Roadster',
      'S5 Cabriolet',
      'A5 Cabriolet',
      'A3 Cabriolet',
      'TTS Roadster',
      'RS 5 Cabriolet',
  ]

  BENTLEY = [
      'Bentayga',
      'Continental GT',
      'Continental GT V8 Coupe',
      'Continental GT V8 S Coupe',
      'Continental GT Coupe',
      'Continental GT Speed Coupe',
      'Grand Convertible',
      'Mulsanne',
      'Flying Spur',
  ]

  BMW = [
      'Z4 Roadster',
      'M6 Convertible',
      'M4 Convertible',
      '2 Series Convertible',
      '4 Series Convertible',
      '6 Series Convertible',
      '1 Series 5-Door',
      '1 Series ActiveE',
      '3 Series Sedan',
      'ActiveHybrid 3',
      '5 Series Sedan',
      'ActiveHybrid 5',
      '7 Series',
      'ActiveHybrid 7',
      'M3 Sedan',
      'M5 Sedan',
      '3 Series Gran Turismo',
      '5 Series Gran Turismo',
      'I3',
      'I8',
      'M4 Coupe',
      'M6 Coupe',
      '1 Series 3 Door',
      '2 Series Coupe',
      '4 Series Coupe',
      '6 Series Coupe',
      'M6 Gran Coupe',
      '4 Series Gran Coupe',
      '6 Series Gran Coupe',
      'X6',
      'X5',
      'X4',
      'X3',
      'X1',
      'X5 M',
      'X6 M',
      '3 Series Touring',
      '5 Series Touring',
      '2 Series Gran Tourer',
      '2 Series Active Tourer',
  ]

  CADILLAC = [
      'SRX Crossover',
      'Escalade ESV',
      'ATS-V',
      'ATS Sedan',
      'CTS Sedan',
      'XTS Sedan',
      'Escalade Hybrid',
      'SRX',
      'XTS',
      'DTS Sedan',
      'Seville',
      'ELR Coupe',
      'ATS Coupe',
      'ATS-V Coupe',
      'CTS-V Coupe',
      'XLR Roadster',
  ]

  CHEVROLET = [
      'Traverse',
      'Equinox',
      'Trax',
      'Suburban',
      'Captiva Sport',
      'Tahoe',
      'Suburban',
      'SS',
      'Cruze',
      'Sonic',
      'Spark',
      'Impala',
      'Malibu',
      'Spark EV',
      'Aveo',
      'Corvette Coupe',
      'Camaro Coupe',
      'Corvette',
      'Camaro',
  ]

  CHRYSLER = [
      'Town & Country',
      'Aspen Hybrid',
      'Pacifica',
      'Voyager',
      '200',
      '300',
      '300C',
      'Delta Coupe',
      'Ypsilon',
      'Nassau',
      'Crossfire',
      'Viper',
      'Stratus',
      '200 Convertible',
      '200 Touring Convertible',
      'Sebring Convertible',
  ]

  CITROEN = [
      'DS 5',
      'DS 4',
      'DS 3',
      'Nemo',
      'Dispatch',
      'Berlingo',
      'C5 Tourer',
      'C5 Saloon',
      'C4 Picasso',
      'C4 Cactus',
      'C3 Picasso',
      'New Relay',
      'DS 3 Cabrio',
      'Grand C4 Picasso',
      'Dispatch Combi',
      'C4 New Range',
  ]

  DODGE = [
      'Durango',
      'Grand Caravan',
      'Journey',
      'Nitro',
      'Caliber',
      'Dart',
      'Avenger',
      'Magnum',
      'Stratus',
      'Neon',
      'Intrepid',
      'Viper',
      'Challenger',
      'Charger',
      'Viper SRT10 Roadster Final Edition',
  ]

  FERRARI = [
      'LaFerrari',
      'FF',
      'FF458 Spider',
      'T458 Speciale',
      'F12berlinetta',
      '458 Speciale A',
      '488 GTB',
      'California',
      '599 GTB Fiorano',
      'F430',
  ]

  FIAT = [
      'Abarth',
      'Panda',
      'Punto',
      'Qubo',
      'Doblo',
      '500 4-Door',
      'Panda 4×4',
      '500 Cabrio',
      '500 Electric',
      '500 Crossover',
      '500 Hatchback',
      'Panda Crossover',
  ]

  FORD = [
      'Explorer',
      'Escape',
      'Edge',
      'Expedition',
      'Flex',
      'Expedition EL',
      'Focus',
      'Fiesta',
      'Taurus',
      'Fusion',
      'Focus ST',
      'C-Max Hybrid',
      'C-Max Energi',
      'Fusion Energi',
      'Mustang',
      'Fusion Hybrid',
      'Shelby GT500 Coupe',
      'Shelby GT500 Convertible',
      'Mustang Convertible',
  ]

  HONDA = [
      'Fit',
      'City',
      'Civic',
      'Fit EV',
      'Accord',
      'Crosstour',
      'FCX Clarity',
      'Civic Hybrid',
      'Accord Hybrid',
      'Accord Plug-In',
      'CR-Z',
      'Vezel',
      'Insight',
      'Civic Coupe',
      'Accord Coupe',
      'Civic Coupe Si',
      'Civic Type-R',
      'CR-V',
      'Pilot',
      'Odyssey',
      'Element',
      'Passport',
      'S2000',
      'Del Sol',
  ]

  HYUNDAI = [
      'Azera',
      'Equus',
      'Sonata',
      'Genesis',
      'Touring',
      'Elantra GT',
      'Sonata Hybrid',
      'Accent',
      'Veloster',
      'Tiburon',
      'Elantra Coupe',
      'Genesis Coupe',
      'Tucson',
      'Santa Fe',
      'Veracruz',
      'Santa Fe Sport',
  ]

  INFINITI = [
      'Q70L',
      'Q70',
      'Q50',
      'Q40',
      'QX50',
      'QX60',
      'QX70',
      'Q60',
      'Q50 Hybrid',
      'QX60 Hybrid',
      'Q70 Hybrid',
      'QX80',
      'Q60 Convertible',
      'Q60 IPL Convertible',
  ]

  JAGUAR = [
      'F-Type Convertible',
      'XK Convertible',
      'F-Type Coupe',
      'XK Coupe',
      'XJR LWB',
      'XFR-S',
      'XF',
      'XJ',
      'XK-Series',
      'X-Type',
      'S-Type',
      'XJR',
      'XJS',
  ]

  KIA = [
      'Rio',
      'K900',
      'Forte',
      'Cadenz',
      'Optima',
      'Forte 5',
      '5-Door',
      'Optima Hybrid',
      'Soul',
      'Sedona',
      'Sorento',
      'Soul EV',
      'Sportage',
      'Soul Red Zone 2.0',
      'Soul Caribbean Blue',
      'Forte Koup',
      'Forte 2-Door',
  ]

  LAMBORGHINI = [
      'Murcielago',
      'Veneno Roadster',
      'Huracan LP 610-4',
      'Aventador LP 700-4',
      'Aventador LP 700-4 Roadster',
      'Gallardo LP 620-2 Super Trofeo',
      'Aventador LP 700-4 Superveloce',
      'Aventador LP 700-4 Pirelli Edition',
  ]

  LAND_ROVER = [
      'LR2',
      'LR4',
      'Discovery',
      'Defender',
      'Freelander',
      'Range Rover',
      'Range Rover Sport',
      'Range Rover Evoque',
      'New Discovery Sport',
  ]

  LEXUS = [
      'RX 270',
      'RX 350',
      'RX 450h',
      'GX 460',
      'GX 400',
      'LX 570',
      'IS 300h',
      'IS 350',
      'IS 250',
      'ES 300h',
      'ES 350',
      'GS 250',
      'GS 350',
      'GS 450h',
      'LS 460',
      'LS 460 L',
      'LS 600h',
      'LS 600h L',
      'CT 200h',
      'HS 250h',
  ]

  MASERATI = [
      'Ghibli',
      'Ghibli S',
      'Ghibli S Q4',
      'GranCabrio',
      'Ghibli Diesel',
      'GranTurismo',
      'Quattroporte S',
      'GranCabrio MC',
      'GranCabrio Sport',
      'Quattroporte GTS',
      'Quattroporte S Q4',
      'GranTurismo Sport',
      'Quattroporte Diesel',
      'GranTurismo MC Stradale',
      'GranCabrio MC Centennial Edition',
      'GranTurismo MC Centennial Edition',
  ]

  MAZDA = [
      '2',
      '3',
      '6',
      '5',
      'Speed 3',
      'MX-5',
      'RX8',
      '6 Coupe',
      'CX-5',
      'CX-9',
      'CX-7',
      'Tribute',
      'Tribute Hybrid',
      'MX-5 Miata',
      'Speed Miata',
  ]

  MERCEDES = [
      'S-Class Sedan',
      'C-Class Sedan',
      'E-Class Sedan',
      'E-Class Hybrid',
      'Maybach S600',
      'B-Class Electric Drive',
      'AMG GT S',
      'E-Class Coupe',
      'SLS AMG',
      'C-Class Coupe',
      'S-Class Coupe',
      'CLA-Class Coupe',
      'CLS-Class Coupe',
      'E-Class Wagon',
      'G-Class SUV',
      'GL-Class SUV',
      'M-Class SUV',
      'GLK-Class SUV',
      'GLA-Class SUV',
      'SL-Class Roadster',
      'SLK-Class Roadster',
      'E-Class Cabriolet',
      'SLR McLaren',
  ]

  MINI = [
      'Coupe',
      'Cooper',
      'Roadster',
      'PACEMAN',
      'Convertible',
      'Countryman',
      '3-Door Hatch',
      '5-Door Hatch',
      'Hardtop 4-Door',
      'Hardtop 2-Door',
      'Clubman Concept',
      'John Cooper Works',
  ]

  MITSUBISHI = [
      'Mirage',
      'I-MiEV',
      'Lancer Sportback',
      'Galant',
      'Lancer',
      'Lancer Evolution X',
      'Eclipse Coupe',
      'Eclipse Spyder',
      'Outlander PHEV',
      'Outlander Sport',
      'Shogun',
      'ASX',
      'Endeavor',
      'Eclipse Convertible',
  ]

  NISSAN = [
      'Maxima',
      'Altima',
      'Cube',
      'Leaf',
      'Sentra',
      'Versa Sedan',
      'Versa Note',
      'Pathfinder Hybrid',
      '370Z Coupe',
      '350Z Coupe',
      '370Z Roadster',
      'GT-R',
      'Armada',
      'Murano',
      'Pathfinder',
      'Xterra',
      'Rogue',
      'Juke',
      'Select',
      'Quest',
      'NV Passenger',
      'Qashqai',
      'Murano Crosscarbiolet',
  ]

  PEUGEOT = [
      '408',
      '301',
      '508',
      '308',
      'iOn',
      '308 GT',
      '208 XY',
      '208 GTi',
      '308 Sedan',
      '208 5-doors',
      '207 5-doors',
      '108 5-doors',
      '508 Hybrid4',
      '3008 Hybrid4',
      'RCZ',
      'RCZ R',
      '208 3-doors',
      '207 3-doors',
      '108 3-doors',
      '4008',
      '3008',
      '2008',
      '5008',
      '508 SW',
      '308 SW',
      '508 RXH',
      '308 GT SW',
      'Expert Tepee',
      'Partner Tepee',
      'Bipper Tepee',
  ]

  PORSCHE = [
      'Cayman',
      'Boxter GTS',
      'Boxter',
      'Macan Turbo',
      'Macan S',
      'Panamera',
      '918 Spyder',
      '911 GT3 RS',
      '911 GT3',
      '911 Turbo S',
      '911 Turbo',
      '911 Targa 4S',
      '911 Targa 4',
      '911 Carrera 4S',
      '911 Carrera 4',
      '911 Carrera S',
      '911 Carrera',
      'Cayman GT4',
      'Cayenne S',
      'Cayenne',
      'Cayman S',
      'Cayenne GTS',
      'Cayman GTS',
      'Panamera 4S',
      'Panamera S',
      'Panamera 4',
      'Panamera GTS',
      'Cayenne Turbo',
      'Cayenne Diesel',
      'Panamera Turbo',
      '911 Targa 4 GTS',
      '911 Carrera GTS',
      'Cayenne Turbo S',
      'Panamera Turbo S',
      '911 Carrera 4 GTS',
      'Cayenne S E-Hybrid',
      '911 Turbo Cabriolet',
      'Panamera S E-Hybrid',
      '911 Carrera Cabriolet',
      '911 Turbo S Cabriolet',
      '911 Carrera 4 Carbiolet',
      'Panamera 4S Exectuive',
      '911 Carrera S Cabriolet',
      '911 Carrera 4S Cabriolet',
      'Panamera Exlusive Series',
      '911 Carrera GTS Cabriolet',
      'Panamera Turbo Executive',
      '911 Carrera 4 GTS Cabriolet',
      'Panamera Turbo S Executive',
      '918 Spyder Weissach Package',
  ]

  RENAULT = [
      'Zoe',
      'Clio',
      'Twizy',
      'Scenic',
      'Captur',
      'Twingo',
      'Clio Renaultsport',
      'Grand Scenic',
      'Scenic XMOD',
      'Megane Renaultsport',
      'Megane Hatch',
      'Megane Coupe',
      'Megane Sport Tourer',
      'Megane Coupe Cabriolet',
  ]

  ROLLS_ROYCE = [
      'Ghost',
      'Series II',
      'Phantom',
      'Wraith',
      'Ghost',
      'Phantom Coupe',
      'Phantom Drophead Coupe',
      'Silver Seraph',
      'Corniche',
  ]

  SAAB = [
      '9-3 Aero',
      '9-3 ePower',
      'Phoenix',
  ]

  SUBARU = [
      'Forester',
      'Exiga',
      'Tribeca',
      'Dex',
      'BRZ',
      'Levorg',
      'Trezia',
      'Legacy B4',
      'Impreza XV',
      'Impreza WRX (VA)',
      'Impreza WRX STI',
      'Pleo',
  ]

  SUZUKI = [
      'Celerio',
      'Splash',
      'Swift',
      'SX4',
      'Ciaz',
      'Kizashi',
      'SX4 S-Cross',
      'Jimmy',
      'Grand Vitara',
      'Ertiga',
      'APV',
  ]

  TOYOTA = [
      'Highlander Hybrid',
      'Land Cruiser',
      'Highlander',
      '4Runner',
      'Sequoia',
      'Sienna',
      'Venza',
      'RAV4',
      'Avalon Hybrid',
      'Avalon',
      'Hybrid',
      'Camry',
      'Corolla',
      'Yaris',
      'Prius Plug-in Hybrid',
      'Highlander Hybrid',
      'Camry Hybrid',
      'Prius V',
      'Prius C',
      'Prius',
      'GT86 Sports Car',
  ]

  VOLKSWAGEN = [
      'CC',
      'GTI',
      'Eos',
      'Golf',
      'Jetta',
      'Tiguan',
      'Passat',
      'Bettle',
      'Golf R',
      'E-Golf',
      'Touareg',
      'Golf GTI',
      'Jetta Hybrid',
      'Touareg Hybrid',
      'Jetta SportWagen',
  ]
end